CAMERA_ID = 0
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
CAMERA_FPS = 30

MEDIAPIPE_MAX_HANDS = 1
MEDIAPIPE_MODEL_PATH = "models/hand_landmarker.task"

SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

PINCH_DISTANCE_THRESHOLD = 0.3
TEMPORAL_WINDOW_SIZE = 15
TEMPORAL_FPS = 30
VELOCITY_THRESHOLD = 0.01
STABILITY_THRESHOLD = 0.7
PINCH_THRESHOLD = 0.3
FINGER_MOTION_THRESHOLD = 0.02

CLICK_HOLD_TIME = 0.15
COOLDOWN_TIME = 0.2
DRAG_MIN_TIME = 0.1
RECENT_APPS_SPREAD_THRESHOLD = 0.16
RECENT_APPS_HOLD_TIME = 0.20
RECENT_APPS_STABILITY_THRESHOLD = 0.65

CURSOR_SENSITIVITY = 1
CURSOR_SMOOTHING_FACTOR = 0.6
MOUSE_PAUSE = 0.01

DEBUG_MODE_DEFAULT = False
MOUSE_ENABLED_DEFAULT = False
SHOW_LANDMARKS = True
SHOW_STATE_INFO = True
SHOW_MOTION_INDICATORS = True
SHOW_FINGER_STATES = True

TARGET_FPS = 30
ENABLE_FPS_COUNTER = True

CUSTOM_STAGE_ONE_SCORE_THRESHOLD = 0.28
CUSTOM_STAGE_TWO_HEATMAP_PEAK_THRESHOLD = 0.10
CUSTOM_GHOST_REJECT_STAGE_ONE_MAX = 0.70
CUSTOM_GHOST_REJECT_PEAK_MAX = 0.14
CUSTOM_STAGE_ONE_INTERVAL = 5
